version: '2.2'

services:
  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: 1
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/app
